### ISSUE TITLE
Passing array Parameter 

### ISSUE THREAD

**Issue by ajoudeh** [christiankerl/ckWebServicePlugin#5]
I would like to thank you about a wonderful SOAP Plugin `ckWebServicePlugin`,
I install it & set require configuration to use it, but I have a problem when I send an array parameter 

My Code:
$client = new nusoap_client('http://localhost/sync/web/MathApi.php?wsdl', true);
$result = $client->call('SimpleMultiply', array(array(5.5,2.6)));

Action:
<?php

// apps/frontend/modules/math/actions/actions.class.php
class mathActions extends sfActions
{
  /**
- An action multiplying two numbers.
  *
- @WSMethod(name='SimpleMultiply', webservice='MathApi')
  *
- @param double[] $a An array of factors
  *
- @return double The result
  */
  
  public function executeMultiply($request)
  {
    $this->result = 2;
  
    foreach($request->getParameter('a') as $factor)
    {
      $this->result *= $factor;
  }
  }

Problem:
• $request->getParameter('factors') is empty no data

Can  you help me Please? 
i follow every step of config? i don't know what's thr wrong?

**Comment by christiankerl** [comment]
can you try using the SoapClient from the PHP soap extension? Otherwise what does the request sent by the nusoap client look like?

**Comment by ajoudeh** [comment]
SoapClient from the PHP:

$client = new SoapClient("http://localhost/sync/web/MathApi.php?wsdl");
$result = $client->SimpleMultiply(array(array(5,9)));

it's return 1 always

Action:
/**
- An action multiplying two numbers.
  *
- @WSMethod(name='SimpleMultiply', webservice='MathApi')
  *
- @param double[] $a An array of factors
  *
- @return double The result
  */
  
  public function executeMultiply($request)
  {
    $this->result = 2;
  
    foreach($request->getParameter('a') as $factor)
    {
      $this->result *= $factor;
    }
  }

**Comment by christiankerl** [comment]
It should be:

```
$result = $client->SimpleMultiply(array(5,9));
```

instead of:

```
$result = $client->SimpleMultiply(array(array(5,9)));
```

does this work better?

Otherwise post the results of the following two lines here: 

```
echo $client->__getLastRequest();
echo $client->__getLastResponse();
```

**Comment by ajoudeh** [comment]
i already write : $result = $client->SimpleMultiply(array(array(5,9)));

& 
echo $client->__getLastRequest();
echo $client->__getLastResponse(); 

return  NULL

**Comment by christiankerl** [comment]
you should only pass an array of doubles to 'SimpleMultiply' instead of array(array(...))

and you have to pass the SoapClient constructor the 'trace' option so `__getLast*` works:

```
$client = new SoapClient('url of wsdl', array('trace' => 1));
```

**Comment by ajoudeh** [comment]
Fatal error: Uncaught SoapFault exception: [HTTP] Internal Server Error in C:\Program Files\Zend\Apache2\htdocs\SOAP\math.php:15 Stack trace: #0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://localhos...', 'http://localhos...', 1, 0) #1 C:\Program Files\Zend\Apache2\htdocs\SOAP\math.php(15): SoapClient->__call('SimpleMultiply', Array) #2 C:\Program Files\Zend\Apache2\htdocs\SOAP\math.php(15): SoapClient->SimpleMultiply(Array) #3 {main} thrown in C:\Program Files\Zend\Apache2\htdocs\SOAP\math.php on line 15

**Comment by ajoudeh** [comment]
it's seem not work with me, i will handling this issue with another way,

thank you very very much

**Comment by sbrutin** [comment]
It could be a problem with your apps/config/filters.yml file.
Check this out : http://blog.adin.pro/2012-12-21/ckwebserviceplugin-empty-params/
